### ISSUE TITLE
BIP002: Proof of crime

### ISSUE THREAD

**Issue by taxmeifyoucan** [Bordel/bips#2]
To establish a web of trust between members, let's make a `proof of crime` an obligation for becoming a member. In order to gain trust of other members, to assure others that newcomer does not collaborate with authorities or does not work for government organs, he must provide a `proof of crime` which will be confidential within web of trust of existing members. This proof doesn't require committing any specific crime. Any morally correct violation of government laws can be accepted.

**Comment by MaxHillebrand** [comment]
conceptACK

**Comment by JosefJ** [comment]
I like the framing; yet I don't think should be a set rule for membership.

**Comment by taxmeifyoucan** [comment]
Let's leave it here as not activated BIP, might be useful as future reference.
