### ISSUE TITLE
BIP003: Add a plotting surface a.k.a. whiteboard

### ISSUE THREAD

**Issue by MaxHillebrand** [Bordel/bips#3]
useful to have for brainstorming.

**Comment by JosefJ** [comment]
Would something like this be enough?
https://amzn.to/349Mx1w

**Comment by taxmeifyoucan** [comment]
@JosefJ that one looks good! I was thinking whiteboard panel on a wall but this seems like a better option since we can move it and there is not enough space on walls anyway. So let's go for it

**Comment by JosefJ** [comment]
We now have a flipchart/whiteboard! :) closing this!
